import { useEffect, useState } from 'react';
import { ArrowUpRight, Check, ChevronDown, CircleHelp, Database, Download, GraduationCap, RefreshCw, Sparkles, X } from 'lucide-react';
import './companion.css';
import './companion-window.css';
import './companion-polish.css';
import './companion-refined.css';
import ModelEditor, {type ManualInput} from './ModelEditor';
import AnimatedNumber from './AnimatedNumber';
import {priceFor, referenceCost, usd} from './pricing';
import '@fontsource/nunito/latin-400.css';
import '@fontsource/nunito/latin-600.css';
import '@fontsource/nunito/latin-700.css';
import '@fontsource/nunito/latin-800.css';

type Row = { originalModel?:string; manualModel?:string; origin?:string; provider?: string; measurement?:string; id: string; title: string; model: string; effort: string; category: string; input: number | null; output: number | null; cache: number | null; cacheWrite?: number | null; calls: number; outcome: string; updated: string; context: number; contextLimit: number; signal?: {state:string;reason:string} };
type Observation = {provider?:string;category:string;model:string;effort:string;count:number;medianTokens:number;cacheRate:number;positive:number;negative:number};
type Group = {provider?:string; category: string; model: string; effort: string; count: number; first: number; successRate: number; medianTokens: number; eligible: boolean };
type Snapshot = { rows: Row[]; observations?: Observation[]; groups: Group[]; connected: boolean; paused: boolean; busy: boolean; error: string; lastScan: string | null; fileCount: number; categories: string[]; quota: null | { observedAt: string; primary?: {used_percent?: number}; secondary?: {used_percent?: number} } };
declare global { interface Window { taskModel?: { snapshot: () => Promise<Snapshot>; connect: (provider?: string) => Promise<void>; pause: () => Promise<void>; evaluate: (id: string, outcome: string, category?: string) => Promise<void>; compact: (value: boolean) => Promise<void>; exportSkill: () => Promise<string | null>; installSkill?: () => Promise<string|null>; saveManual?: (data:ManualInput)=>Promise<unknown>; minimize: () => Promise<void>; hide: () => Promise<void> } } }
const empty: Snapshot = { rows: [], groups: [], connected: false, paused: false, busy: false, error: '', lastScan: null, fileCount: 0, categories: [], quota: null };
const number = (value: number | null) => value === null ? '—' : new Intl.NumberFormat('pt-BR', { notation: value > 9999 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value);
const automaticLabel = (row: Row) => ({positive:'Funcionou',first:'De primeira',adjusted:'Com ajustes',negative:'Não funcionou'} as Record<string,string>)[row.signal?.state || ''] || 'Sem confirmação';
const resultLabel = (row: Row) => row.outcome === 'pending' ? `${automaticLabel(row)} · automático` : `${({first:'De primeira',adjusted:'Com ajustes',failed:'Não funcionou'} as Record<string,string>)[row.outcome]} · manual`;
const modelName = (value: string) => value.replace(/^gpt-/, 'GPT ').replace(/-/g, ' ');
function PriceReference({ entries }: {entries: Row[]}) {
  const provider = entries[0].provider || 'Codex';
  const price = priceFor(provider, entries[0].model);
  if (!price) return <p className="price-unavailable">Preço oficial não cadastrado para este modelo nesta origem.</p>;
  const cost = referenceCost(provider === 'Claude Code' ? entries.filter(r => typeof r.cacheWrite === 'number') : entries, price);
  return <div className="price-reference"><div className="price-reference-head"><span>Preço de referência da API</span><small>USD / 1 milhão de tokens</small></div><dl><div><dt>Entrada</dt><dd>{usd(price.input)}</dd></div><div><dt>Cache lido</dt><dd>{usd(price.cached)}</dd></div><div><dt>Saída</dt><dd>{usd(price.output)}</dd></div></dl>{cost && <p><strong>{usd(cost.usd)}</strong> estimados em {cost.count} de {entries.length} registros com contadores completos.</p>}<small>{provider === 'Codex' ? 'Estimativa usa preços padrão de contexto curto; cache criado, ferramentas e outras variações podem não estar nos registros.' : 'Estimativa usa cache criado de 5 min quando registrado; outras durações e variações podem alterar o valor.'} Preço de API não representa cobrança do plano.</small><a href={price.source} target="_blank" rel="noreferrer">Fonte oficial · conferida em {price.checked} ↗</a></div>;
}
export default function Companion() {
  const [data, setData] = useState<Snapshot>(empty);
  const [message, setMessage] = useState('');
  const [tab, setTab] = useState('activity');
  const [insightView, setInsightView] = useState('models');
  const [search, setSearch] = useState('');
  const [provider, setProvider] = useState('Todos');
  const [model, setModel] = useState('Todos');
  const [selected, setSelected] = useState('');
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const isCompact = location.hash === '#companion' && !new URLSearchParams(location.search).has('preview');
  const api = window.taskModel;
  const refresh = async () => { if (api) setData(await api.snapshot()); };
  useEffect(() => { void refresh().catch(() => setMessage('Falha ao ler o histórico.')); const timer = setInterval(() => void refresh().catch(() => {}), 2500); return () => clearInterval(timer); }, []);
  async function act(action: () => Promise<unknown>) { setSaving(true); try { await action(); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Não foi possível concluir.'); } finally { setSaving(false); } }
  const scoped = data.rows.filter(r => (provider === 'Todos' || (r.provider || 'Codex') === provider) && (model === 'Todos' || r.model === model));
  const models = [...new Set(data.rows.filter(r => provider === 'Todos' || (r.provider || 'Codex') === provider).map(r => r.model))].sort();
  const row = scoped.find(r => r.id === selected) || scoped[0];
  const matches = (r: {provider?:string;model:string}) => (provider === 'Todos' || (r.provider || 'Codex') === provider) && (model === 'Todos' || r.model === model);
  const groups = data.groups.filter(matches);
  const obs = (data.observations || []).filter(matches);
  const filtered = scoped.filter(r => `${r.title} ${r.model} ${r.category}`.toLowerCase().includes(search.toLowerCase()));
  return <main className={`companion-shell ${isCompact ? 'compact' : ''}`}>
    <header className="companion-head"><div className="companion-brand"><img src="./brand/task-model-mark.png" alt=""/><span>Task Model<small>Aprendizado local</small></span></div></header>
    {!isCompact && api && !new URLSearchParams(location.search).has('preview') && <p className="companion-footnote"><a href="#journal">Abrir diário manual e comparação ↗</a> · Os registros manuais são separados das etapas importadas.</p>}
    {data.connected && data.paused && <div className="companion-paused" role="status">Coleta pausada <button onClick={() => void act(() => api!.pause())}>Retomar</button></div>}
    {message && <div className="companion-notice" role="status">{message}<button aria-label="Dispensar aviso" onClick={() => setMessage('')}><X/></button></div>}
    {data.error && <p role="alert" className="companion-notice">{data.error}<button onClick={() => void act(() => api!.connect())}>Reconectar</button></p>}
    <div className="companion-workspace"><section className="provider-picker" aria-label="Filtros de origem e modelo">
      <div className="workspace-heading"><h2>Workspace</h2><p>Escolha um aplicativo</p></div>
      <div className="provider-cards" role="group" aria-label="Aplicativo">{[['Codex','openai','OpenAI'],['Claude Code','claude','Anthropic'],['Cursor','cursor','Editor']].map(([name,logo,subtitle])=><button key={name} aria-label={provider===name?`${name} selecionado; clique novamente para ver todos`:name} aria-pressed={provider===name} title={provider===name?'Clique novamente para ver todos':name} onClick={()=>{setProvider(provider===name?'Todos':name);setModel('Todos');setSelected('');setEditing(false);}}><img src={'./brand/'+logo+'.svg'} alt=""/><strong>{name}</strong><small>{subtitle}</small>{provider===name && <Check className="provider-check" size={14}/>}</button>)}</div>
      {provider !== 'Todos' && <button className="provider-connect" onClick={()=>void act(()=>api!.connect(provider))}>Conectar {provider}<ArrowUpRight size={15}/></button>}
      {provider === 'Cursor' && <small className="provider-note">Requer o hook local. Tokens não disponíveis nesta integração inicial.</small>}
    </section><div className="workspace-main">
    {!data.connected ? <section className="companion-welcome"><div className="companion-orb"><Sparkles/></div><h1>Cada tarefa ensina<br/>qual modelo escolher.</h1><p>Acompanhe o consumo e marque o que funcionou. Seu histórico passa a orientar as próximas escolhas.</p><div className="companion-permission"><Database/><span>Leitura dos registros locais do Codex. Guardamos contadores e até 220 caracteres do pedido no seu computador.</span></div><button className="companion-primary" disabled={!api || saving} onClick={() => void act(() => api!.connect())}>Conectar pasta do Codex <ArrowUpRight size={17}/></button><small>{api ? 'Selecione a pasta .codex/sessions. Sem chave de IA.' : 'Abra a versão desktop para conectar o histórico.'}</small></section> : <>
      <div className="workspace-toolbar">
      <nav className="companion-tabs" aria-label="Painel local">{[['activity', 'Agora'], ['history', 'Histórico'], ['insights', 'Aprendizados']].map(([id, label]) => <button key={id} aria-current={tab === id ? 'page' : undefined} onClick={() => setTab(id)}>{label}</button>)}</nav>
        {tab !== 'activity' && <details className="model-picker" key={provider}><summary><span>{model === 'Todos' ? 'Todos os modelos' : model}</span><ChevronDown size={16}/></summary><div className="provider-heading"><span>{provider === 'Todos' ? 'Modelos do histórico' : 'Modelos · '+provider}</span><small>{models.length} registrados</small></div><div className="model-chips" role="group" aria-label="Modelo registrado"><button aria-pressed={model==='Todos'} onClick={()=>{setModel('Todos');setSelected('');}}>Todos os modelos</button>{models.map(m=><button key={m} title={m} aria-pressed={model===m} onClick={()=>{setModel(m);setSelected('');setEditing(false);}}>{m}</button>)}</div>{!models.length && <p>Nenhum modelo registrado nesta origem ainda.</p>}</details>}
      </div>
      <div className="companion-body" key={tab}>
        {tab === 'activity' && <ModelEditor key={row?.id || 'empty'} row={row} onSave={async input=>{if(!api?.saveManual)throw Error('Disponível no aplicativo desktop.');await api.saveManual(input);await refresh();}}/>}
        {tab === 'insights' && <header className="insights-heading"><span className="companion-section-label">LEITURA DO SEU HISTÓRICO</span><h1>Aprendizado local</h1><p>Explore o uso dos modelos, descubra onde os tokens se concentram e veja sugestões baseadas nas suas avaliações.</p><nav className="insights-nav" aria-label="Seções de aprendizados">{[['models','Modelos'],['tasks','Tarefas'],['learning','Sugestões']].map(([id,label])=><button key={id} aria-current={insightView===id?'page':undefined} onClick={()=>setInsightView(id)}>{label}</button>)}</nav></header>}
        {tab === 'insights' && insightView === 'models' && <section className="model-totals"><h2>Consumo por modelo</h2><p className="companion-intro">Somente modelos observados no histórico. Totais parciais quando faltam contadores; tokens não equivalem à cota do plano.</p>{!scoped.length && <div className="companion-empty"><CircleHelp/><h3>Nenhum modelo neste filtro</h3><p>Conecte uma fonte ou escolha outro modelo para ver os contadores e preços.</p></div>}{[...new Set(scoped.map(r=>`${r.provider || 'Codex'}|${r.model}`))].map(key=>{const entries=scoped.filter(r=>`${r.provider || 'Codex'}|${r.model}`===key);const total=(field:'input'|'output'|'cache')=>{const values=entries.map(r=>r[field]).filter((n):n is number=>typeof n==='number');return values.length?values.reduce((a,b)=>a+b,0):null;};return <article className="companion-learning" key={key}><small>{entries[0].provider || 'Codex'} · {entries.length} registros</small><h3>{entries[0].model}</h3><dl className="companion-metrics">{(['input','output','cache'] as const).map((f,i)=><div key={f}><dt>{['Entrada','Saída','Cache lido'][i]}</dt><dd>{number(total(f))}</dd></div>)}</dl><p>{entries.some(r=>r.input===null || r.output===null || r.cache===null)?'Dados incompletos · — significa não disponível.':'Cache lido já incluído na entrada.'}</p><PriceReference entries={entries}/></article>;})}</section>}
        {tab === 'insights' && insightView === 'tasks' && <section className="consumption-insights"><div className="companion-section-label">CONSUMO IMPORTADO AUTOMATICAMENTE</div><h2>Onde seus tokens estão indo</h2><p className="companion-intro">Categorias estimadas pelo pedido, ordenadas pelo consumo total. Você pode corrigir a categoria em Agora. Esforço não representa dificuldade.</p>{!obs.length && <div className="companion-empty"><CircleHelp/><h3>Sem consumo detalhado</h3><p>Esta fonte ainda não trouxe tokens suficientes para mostrar os padrões por tarefa.</p></div>}{obs.map(g => <article className="companion-learning" key={`${g.provider}-${g.category}-${g.model}-${g.effort}`}><small>{g.provider || 'Codex'} · {g.category} · {g.count} etapas</small><h3>{modelName(g.model)} <em>{g.effort}</em></h3><strong>{number(g.medianTokens)} <small>tokens por etapa (mediana)</small></strong><p>{Math.round(g.cacheRate * 100)}% da entrada em cache · {g.positive} sinais positivos · {g.negative} negativos</p></article>)}</section>}
        {tab === 'activity' && (row ? <><div className="companion-section-label">ÚLTIMA ETAPA OBSERVADA <span>{new Date(row.updated).toLocaleTimeString('pt-BR', {hour:'2-digit', minute:'2-digit'})}</span></div><article className="companion-task"><div className="companion-model"><span/>{row.provider || 'Codex'} · {modelName(row.model)}<em>{row.effort}</em></div><h2>{row.title}</h2><label className="companion-category">Categoria<select aria-label="Categoria da etapa" value={row.category} disabled={saving} onChange={e => void act(() => api!.evaluate(row.id, row.outcome, e.target.value))}>{data.categories.map(c => <option key={c}>{c}</option>)}</select><ChevronDown size={14}/></label><div className="companion-total"><strong><AnimatedNumber key={row.id + '-total'} value={row.input === null || row.output === null ? null : row.input + row.output} format={number}/></strong><span>tokens processados<br/>nesta etapa</span></div><dl className="companion-metrics"><div><dt>Entrada</dt><dd><AnimatedNumber key={row.id + '-input'} value={row.input} format={number}/></dd></div><div><dt>Cache¹</dt><dd><AnimatedNumber key={row.id + '-cache'} value={row.cache} format={number}/></dd></div><div><dt>Saída</dt><dd><AnimatedNumber key={row.id + '-output'} value={row.output} format={number}/></dd></div></dl><small className="companion-footnote">¹ Cache lido, incluído na entrada quando disponível · {row.calls} registros observados{row.measurement && <><br/>{row.measurement}</>}</small></article><section className="companion-evaluation"><h3>{resultLabel(row)}</h3><p>{row.outcome === 'pending' ? 'Acompanhamento automático. Corrija somente se precisar.' : 'Sua correção prevalece sobre a leitura automática.'}</p><button onClick={() => setEditing(!editing)}>{editing ? 'Cancelar' : 'Corrigir resultado'}</button>{row.outcome !== 'pending' && <button onClick={() => void act(() => api!.evaluate(row.id, 'pending'))}>Voltar ao automático</button>}{editing && <div>{[['first','De primeira',Check],['adjusted','Com ajustes',RefreshCw],['failed','Não funcionou',X]].map(([value, label, Icon]) => { const Glyph = Icon as typeof Check; return <button key={value as string} disabled={saving} aria-pressed={row.outcome === value} onClick={() => void act(() => api!.evaluate(row.id, value as string).then(() => setEditing(false)))}><Glyph size={17}/>{label as string}</button>; })}</div>}</section></> : <div className="companion-empty"><RefreshCw/><h2>{data.busy ? 'Lendo suas sessões…' : 'Nenhum registro neste filtro'}</h2><p>As etapas aparecem quando os registros contêm um pedido e contadores de consumo.</p></div>)}
        {tab === 'history' && <><input className="companion-search" aria-label="Buscar histórico" placeholder="Buscar tarefa, modelo ou categoria" value={search} onChange={e => setSearch(e.target.value)}/><p className="companion-footnote">{filtered.length} etapas · até 200 arquivos recentes por leitura</p><div className="companion-history">{filtered.slice(0, 100).map(item => <button key={item.id} onClick={() => { setSelected(item.id); setTab('activity'); }}><span><strong>{item.title}</strong><small>{item.provider || 'Codex'} · {modelName(item.model)} · {item.effort} · {item.category}</small><small>{new Date(item.updated).toLocaleString('pt-BR')} · {resultLabel(item)}</small></span><b>{number(item.input === null || item.output === null ? null : item.input + item.output)}<small>tokens</small></b></button>)}</div></>}
        {tab === 'insights' && insightView === 'learning' && <><div className="companion-section-label">RESULTADOS AVALIADOS</div><h2>Sugestões por tarefa</h2><p className="companion-intro">Compare combinações após avaliar seus resultados. Cinco avaliações e 80% de sucesso são o mínimo para uma sugestão inicial.</p>{!groups.length && <div className="companion-empty"><CircleHelp/><h3>Qualidade ainda não confirmada</h3><p>Avalie algumas etapas para começar. Nenhum modelo é recomendado sem evidência.</p></div>}{groups.map(g => <article className="companion-learning" key={`${g.provider}-${g.category}-${g.model}-${g.effort}`}><small>{g.provider || 'Codex'} · {g.category} · {g.eligible ? 'Evidência inicial' : 'Amostra insuficiente ou sucesso abaixo de 80%'}</small><h3>{modelName(g.model)} <em>{g.effort}</em></h3><p>{g.count} avaliações · {Math.round(g.successRate * 100)}% de sucesso</p><strong>{number(g.medianTokens)} <small>tokens por etapa (mediana)</small></strong></article>)}<section className="companion-skill"><GraduationCap aria-hidden="true"/><h3>Task Model — Orientador de modelos</h3><p>Exporte um SKILL.md com resumo do histórico e referências. Funciona neste computador ou como uma cópia portátil, sem API de IA.</p><button className="companion-primary" disabled={saving} onClick={() => void act(async () => { const folder = await api!.exportSkill(); if (folder) setMessage(`Skill criada em ${folder}. Use o SKILL.md no chat ou instale a pasta no agente.`); })}><Download size={16}/>Exportar pacote</button><button className="companion-primary" disabled={saving} onClick={()=>void act(async()=>{if(!api?.installSkill)throw Error('Instalação disponível no aplicativo desktop.');const folder=await api.installSkill();if(folder)setMessage('Skill instalada/atualizada em '+folder+'. Recarregue as skills no agente.');})}>Instalar / atualizar</button><small>Compatível com agentes que leem SKILL.md e arquivos locais. A skill sugere; não troca o modelo.</small></section></>}
      </div>
      {data.quota && provider !== 'Claude Code' && provider !== 'Cursor' && <div className="companion-quota">Última cota do Codex: {data.quota.primary?.used_percent ?? '—'}% na janela curta · {data.quota.secondary?.used_percent ?? '—'}% na longa<small>{new Date(data.quota.observedAt).toLocaleString('pt-BR')} · pode estar desatualizada; não é consumo desta tarefa.</small></div>}
    </>}</div></div>
  </main>;
}
